apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VDsZmSCIls8xuGfj0GieXezfADC93g4AAQbobzDMABnIhexfn9peieyF298IqgIcoRl3lrtvwPO3W+bvy5vGCQ4qzXMnnQe0NLAZsgGXAkGMWkgoKPM6PDYTpKKEBDjkN4C6W5Cxb6SBJhbo/u+BN09D0nsnc77NpgAKE2mAMtnyqEm426ZQ+oAEJcpz9RW+uO2auMT/9HighAfy4Wa26ZsNPWL8NHbsc230VT2Z5xHP3SvXdoGxNPNkrI7NURcQlAmyTZjrRgAiol30E+mHO0ylBE08/mUxRo1w1fHkujEXO1YxOB4JMTI8zluVv9Grp8IGOHs7E6UfrW+v+SuWPKO/V3gp2KHaePFESFYyMnlfw7rHybi4C4thXfhg8GkdSuic0yKd4TJDHxOEk66hhPXca9kA5JMCsq6j+/25NgyYp/dsHk5iN+rfQCuz9M73LtTXbg==,iv:OIiEDat2sb6j//W/zyaWRYL/sxpdWp+TvBHP1FNDNes=,tag:HH18gkoVmmREzv/yHtXR4w==,type:str]
kind: Secret
metadata:
    name: acr-secret
    namespace: bmo
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-04T03:35:21Z"
    mac: ENC[AES256_GCM,data:W6B7lssPDDw+kgRBfJIcf9zyc1Vj7n2JnI+FPlDpVTvNOel0TPj8ej8I9i1IguCw6N879uqHKT6KVu5GgGs1DeXhHrlCS/lahHpkVABFCt9JfcCT9GnrhuDfTRMh7jKyWRjgiwfl/4XjMffh0vf7Mbo4Z7rEr3xPyoxKGXb2tgM=,iv:eazvOQKIT/6gvziU7T8en0+yaiS5P+OobgGke4b0q1g=,tag:2zQmuyWjXPmI1MGf/bAG4A==,type:str]
    pgp:
        - created_at: "2026-03-04T03:35:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3IluRsiqjCqAQv/TmgM798GfP0ogVpbrN40U9CiUY6sM5vcmG7AdICl36K/
            iRHa2Qsx+6msYr+TYjWEEepbdfJjEvOTq611WrjUEjsSoze1HrjpBHubbr0ikyI7
            SkC5o5rW5nD5sVzol1UMCHi2V4epsLRCqtV3zIcwdzxaru9di1C6sUxAiVbz6q1A
            DPycQLlZowIV3zuOVYmuMVq7UZ0sWziEZwVETZwqrCmRh+51d+xuQFDvx5baTbvV
            H7d1kMZ4GlR+OYbmmwcT9oG20sP3Are9rkZnO6jFtKLD4ejpzxH9GmaxcYr2hHtk
            dsez/DnXL+wcjtIQvMpiR4M/coxCtr6j0ZUVjaCh7eGTYHSE72sud7odw+7wcL7b
            cvcCzVs8EVg1kaqhBZAaIl61QApsZKjhF+9wPjhoW8CpgEMakO4W6YwM4eGCOsL2
            lluvHa57nLXPP6mxaDeh8uFu260lMAPaLj7/sIH3uUmIF8CfGcnoI1LYNOkNKZ8S
            sVJEpu/KkYCGZ57rqCSn1GgBCQIQ1PUnsj7tazKMOnMHQcKiho7dxf/ZI8KSAnGb
            AB+Z4grI4hV8tKFKSOCEN2k0TWYL06S3QFD1dEhNYRvrXC/ciqmpLIg0tJDHAzTr
            zSD6Ow9aj0gNXPsEAoTeZsdKWdR3TaQAIA==
            =7S4Y
            -----END PGP MESSAGE-----
          fp: 290495DC18795377
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
