apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: backend-image
  namespace: flux-system
spec:
  image: bmodemoacr.azurecr.io/backendapp
  interval: 2m
  secretRef:
    name: acr-secret
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend-image
  policy:
    semver:
      range: ">=v1.0.0"
