apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: bmo
spec:
  replicas: 3
  containers:
    - name: backend
      image: bmodemoacr.azurecr.io/backendapp:v2.0.0 # {"$imagepolicy": "flux-system:backend-policy"}  
